### PR TITLE
Update to django 1.9+

### PR DESCRIPTION
**Pull request by katomaso**
Hello, 
I propose an update to your nice project to keep it up-to-date.

Cheers,
Tom

### CODE REVIEW

**Comment by riklaunim** [comment]
This fields:
```
created = models.DateTimeField(auto_now_add=True)
```
should not be secretly added ;)

**Comment by katomaso** [comment]
I didn't realized it sneaked in. This field adds possibility to find out when exactly are your customers hitting your website. Should I remove it or do you think it is an interesting information to have there?

**Comment by riklaunim** [comment]
If it would have to be added it has to have a migration. There is also the date field, so trying to replace it with datetime field is a good option too. We can do some backward incompatible changes and do a major number bump.

**Comment by katomaso** [comment]
Well I redid migrations from scratch to use django's built in migrations. South is obsolete project now. I think it is a good idea to gather metrics with variable resolution instead of hard-coded daily stats. I'd keep the created field now and add the variable resolution in a few days.

**Comment by katomaso** [comment]
I removed the new field so we remain backward compatible. Would you accept this pull request?

**Comment by riklaunim** [comment]
Yes, I will. I just need some free time to get to this, update, test and release :)

**Pull request merged**
